"""Build and update a podcast RSS 2.0 feed (with iTunes namespace).

podcast.xml is committed to the repo root. Subscribers paste the raw
GitHub URL into any podcast app:
  https://raw.githubusercontent.com/{owner}/{repo}/main/podcast.xml
"""

import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List

_ITUNES_NS = "http://www.itunes.com/dtds/podcast-1.0.dtd"
_CHANNEL_TITLE = "AI Skills Weekly"
_CHANNEL_DESCRIPTION = (
    "Weekly audio digest of the latest AI developer tools, repos, and releases on GitHub. "
    "Auto-generated by the daily-ai-docs pipeline."
)

# Register namespace prefix so ET serialises it as itunes:xxx
ET.register_namespace("itunes", _ITUNES_NS)


def _itunes(tag: str) -> str:
    return f"{{{_ITUNES_NS}}}{tag}"


def _rfc2822(dt: datetime) -> str:
    """Format datetime as RFC 2822 string required by RSS pubDate."""
    return dt.strftime("%a, %d %b %Y %H:%M:%S +0000")


def render_feed(
    episodes: List[Dict],
    channel_link: str = "https://github.com",
) -> str:
    """Build a full RSS 2.0 + iTunes podcast feed XML string.

    Each episode dict must contain:
      title (str), mp3_url (str), pub_date (str, YYYY-MM-DD),
      duration_secs (int), description (str), guid (str)
    """
    rss = ET.Element("rss", {"version": "2.0"})
    channel = ET.SubElement(rss, "channel")

    ET.SubElement(channel, "title").text = _CHANNEL_TITLE
    ET.SubElement(channel, "link").text = channel_link
    ET.SubElement(channel, "description").text = _CHANNEL_DESCRIPTION
    ET.SubElement(channel, "language").text = "en-us"
    ET.SubElement(channel, _itunes("author")).text = _CHANNEL_TITLE
    ET.SubElement(channel, _itunes("summary")).text = _CHANNEL_DESCRIPTION
    ET.SubElement(channel, _itunes("explicit")).text = "false"

    for ep in episodes:
        item = ET.SubElement(channel, "item")
        ET.SubElement(item, "title").text = ep["title"]
        ET.SubElement(item, "guid", {"isPermaLink": "false"}).text = ep["guid"]
        ET.SubElement(item, "description").text = ep.get("description", "")
        ET.SubElement(item, _itunes("summary")).text = ep.get("description", "")

        # Format pub_date (YYYY-MM-DD) → RFC 2822
        try:
            dt = datetime.strptime(ep["pub_date"], "%Y-%m-%d").replace(tzinfo=timezone.utc)
            ET.SubElement(item, "pubDate").text = _rfc2822(dt)
        except (ValueError, KeyError):
            ET.SubElement(item, "pubDate").text = ep.get("pub_date", "")

        ET.SubElement(
            item,
            "enclosure",
            {
                "url": ep["mp3_url"],
                "length": str(ep.get("file_size_bytes", 0)),
                "type": "audio/mpeg",
            },
        )
        mins, secs = divmod(int(ep.get("duration_secs", 0)), 60)
        ET.SubElement(item, _itunes("duration")).text = f"{mins}:{secs:02d}"

    return ET.tostring(rss, encoding="unicode", xml_declaration=False)


def load_episodes(path: str = "podcast.xml") -> List[Dict]:
    """Parse an existing podcast.xml and return its episodes as dicts."""
    p = Path(path)
    if not p.exists():
        return []
    try:
        tree = ET.parse(p)
        episodes: List[Dict] = []
        for item in tree.findall(".//item"):
            enc = item.find("enclosure")
            guid_el = item.find("guid")
            title_el = item.find("title")
            pub_el = item.find("pubDate")
            dur_el = item.find(_itunes("duration"))
            desc_el = item.find("description")
            episodes.append(
                {
                    "title": title_el.text if title_el is not None else "",
                    "guid": guid_el.text if guid_el is not None else "",
                    "mp3_url": enc.get("url", "") if enc is not None else "",
                    "file_size_bytes": int(enc.get("length", 0)) if enc is not None else 0,
                    "pub_date": (pub_el.text or "")[:16] if pub_el is not None else "",
                    "duration_secs": 0,
                    "duration_str": dur_el.text if dur_el is not None else "0:00",
                    "description": desc_el.text if desc_el is not None else "",
                }
            )
        return episodes
    except ET.ParseError:
        return []


def write_feed(
    episodes: List[Dict],
    path: str = "podcast.xml",
    channel_link: str = "https://github.com",
) -> Path:
    """Write a podcast feed to disk and return its Path."""
    xml_str = render_feed(episodes, channel_link=channel_link)
    # Prepend XML declaration manually for podcast app compatibility
    content = '<?xml version="1.0" encoding="UTF-8"?>\n' + xml_str + "\n"
    out = Path(path)
    out.write_text(content, encoding="utf-8")
    return out


def prepend_episode(
    episode: Dict,
    path: str = "podcast.xml",
    channel_link: str = "https://github.com",
) -> Path:
    """Load existing feed, prepend a new episode (newest first), and write."""
    existing = load_episodes(path)
    # Avoid duplicates by guid
    existing = [e for e in existing if e.get("guid") != episode.get("guid")]
    updated = [episode] + existing
    return write_feed(updated, path=path, channel_link=channel_link)
